/********************************************************************
* McDst_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error McDst_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMcDst_Dict();
extern void G__cpp_setup_inheritanceMcDst_Dict();
extern void G__cpp_setup_typetableMcDst_Dict();
extern void G__cpp_setup_memvarMcDst_Dict();
extern void G__cpp_setup_globalMcDst_Dict();
extern void G__cpp_setup_memfuncMcDst_Dict();
extern void G__cpp_setup_funcMcDst_Dict();
extern void G__set_cpp_environmentMcDst_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "McEvent.h"
#include "McArrays.h"
#include "McDstReader.h"
#include "McDst.h"
#include "McDstCut.h"
#include "McPIDConverter.h"
#include "McDstQA.h"
#include "McRun.h"
#include "McParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__McDst_DictLN_TClass;
extern G__linked_taginfo G__McDst_DictLN_TBuffer;
extern G__linked_taginfo G__McDst_DictLN_TMemberInspector;
extern G__linked_taginfo G__McDst_DictLN_TObject;
extern G__linked_taginfo G__McDst_DictLN_TNamed;
extern G__linked_taginfo G__McDst_DictLN_TString;
extern G__linked_taginfo G__McDst_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__McDst_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McDst_DictLN_TClonesArray;
extern G__linked_taginfo G__McDst_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__McDst_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__McDst_DictLN_TLorentzVector;
extern G__linked_taginfo G__McDst_DictLN_McEvent;
extern G__linked_taginfo G__McDst_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__McDst_DictLN_TTree;
extern G__linked_taginfo G__McDst_DictLN_TFile;
extern G__linked_taginfo G__McDst_DictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__McDst_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__McDst_DictLN_TChain;
extern G__linked_taginfo G__McDst_DictLN_McParticle;
extern G__linked_taginfo G__McDst_DictLN_McDst;
extern G__linked_taginfo G__McDst_DictLN_McRun;
extern G__linked_taginfo G__McDst_DictLN_McDstReader;
extern G__linked_taginfo G__McDst_DictLN_McDstCut;
extern G__linked_taginfo G__McDst_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__McDst_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McDst_DictLN_McPIDConverter;
extern G__linked_taginfo G__McDst_DictLN_McPIDConvertercLcLEConvention;
extern G__linked_taginfo G__McDst_DictLN_maplEunsignedsPintcOmaplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__McDst_DictLN_TH1F;
extern G__linked_taginfo G__McDst_DictLN_TH2F;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__McDst_DictLN_TParticle;
extern G__linked_taginfo G__McDst_DictLN_McDstQA;

/* STUB derived class for protected member access */
